#pragma once

enum alt_keycodes {
    MD_BOOT = SAFE_RANGE,
    LAYER_TOGGLE,
    PYCHARM_COMMENT,
    PYCHARM_PREV_TAB,
    PYCHARM_NEXT_TAB,
    PYCHARM_PREV_CHANGE,
    PYCHARM_NEXT_CHANGE,
    PYCHARM_REFORMAT,
    PYCHARM_TOGGLE_CASE,
    PYCHARM_FIND_USAGES,
    PYCHARM_SETTINGS,
    PYCHARM_GO_TO_DECLARATION,
    PYCHARM_TRANSPOSE
};
